# Generated by Django 4.1.6 on 2023-02-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_omborg_galla'),
    ]

    operations = [
        migrations.AddField(
            model_name='galla',
            name='tr_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
