# Generated by Django 4.1.6 on 2023-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_paxta_ifloslik_alter_paxta_namlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='omborg',
            name='icon',
            field=models.ImageField(blank=True, default='img/DEFAULT.ico', null=True, upload_to='icon'),
        ),
    ]
