# Generated by Django 4.1.6 on 2023-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_omborg_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='galla',
            name='imzo',
            field=models.BooleanField(default=False),
        ),
    ]
