# Generated by Django 4.1.6 on 2023-02-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_galla_imzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='omborg',
            name='reja',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='omborg',
            name='sentner',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='galla',
            name='ombor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Home.omborg'),
        ),
        migrations.AlterField(
            model_name='galla',
            name='sofVazn',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='galla',
            name='tr_marka',
            field=models.CharField(blank=True, choices=[('ЗИЛ', 'ЗИЛ'), ('КАМАЗ', 'КАМАЗ'), ('БОШКА', 'БОШКА')], max_length=20),
        ),
        migrations.AlterField(
            model_name='galla',
            name='tr_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='galla',
            name='tr_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='galla',
            name='yuk_num',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
