# Generated by Django 4.1.7 on 2023-02-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_omborg_reja_omborg_sentner_alter_galla_ombor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XarajatRejasi',
        ),
    ]
