# Generated by Django 4.1.7 on 2023-02-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_delete_xarajatrejasi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XarajatTuri',
            new_name='Xarajat',
        ),
    ]
