# Generated by Django 4.1.7 on 2023-02-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_rename_xarajatturi_xarajat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xar_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ПАХТА', 'ПАХТА'), ('ГАЛЛА', 'ГАЛЛА'), ('СЕМИЧКА', 'СЕМИЧКА'), ('БОШКА', 'БОШКА')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Maxsulot',
        ),
        migrations.RemoveField(
            model_name='xarajat',
            name='name',
        ),
        migrations.AddField(
            model_name='xarajat',
            name='brigada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.brigada'),
        ),
        migrations.AddField(
            model_name='xarajat',
            name='kolvo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='xarajat',
            name='narx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='xarajat',
            name='summa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='xarajat',
            name='turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.xar_turi'),
        ),
    ]
