# Generated by Django 4.1.7 on 2023-02-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_remove_xarajat_turi_delete_xar_turi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xarajat_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='xarajat',
            name='turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.xarajat_t'),
        ),
        migrations.AddField(
            model_name='xarajat',
            name='xarajat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.turx'),
        ),
    ]
