# Generated by Django 4.1.7 on 2023-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_turx_xarajat_t_xarajat_turi_xarajat_xarajat'),
    ]

    operations = [
        migrations.AddField(
            model_name='xarajat',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='summa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
