# Generated by Django 4.1.7 on 2023-02-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_xarajat_name_alter_xarajat_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xarajat',
            name='name',
        ),
    ]
