# Generated by Django 4.1.7 on 2023-02-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_remove_xarajat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xarajat',
            name='brigada',
        ),
        migrations.RemoveField(
            model_name='xarajat',
            name='turi',
        ),
        migrations.RemoveField(
            model_name='xarajat',
            name='xarajat',
        ),
        migrations.DeleteModel(
            name='TurX',
        ),
        migrations.DeleteModel(
            name='Xarajat',
        ),
        migrations.DeleteModel(
            name='Xarajat_t',
        ),
    ]
