# Generated by Django 4.1.7 on 2023-02-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_remove_xarajat_brigada_remove_xarajat_turi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Narxnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_turi', models.CharField(max_length=200)),
                ('narxi', models.FloatField()),
                ('brlik', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ishxaqqi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.FloatField()),
                ('summa', models.FloatField()),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.brigada')),
                ('ish_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.narxnoma')),
                ('xarajat_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.maxsulot')),
            ],
        ),
    ]
