# Generated by Django 4.1.7 on 2023-02-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_bajarilganishlar_n_summa_and_more'),
        ('Home', '0022_lavozim_bolim_xodimlar_ishxaqqi_xodimlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigada',
            name='ish_turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='information.narxnomas'),
        ),
    ]
