# Generated by Django 4.1.7 on 2023-02-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_bajarilganishlar_n_summa_and_more'),
        ('Home', '0023_brigada_ish_turi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigada',
            name='ish_turi',
        ),
        migrations.AddField(
            model_name='brigada',
            name='ish_turi',
            field=models.ManyToManyField(null=True, to='information.narxnomas'),
        ),
    ]
