# Generated by Django 4.1.7 on 2023-02-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_remove_brigada_ish_turi_brigada_ish_turi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigada',
            name='ish_turi',
        ),
        migrations.RemoveField(
            model_name='brigada',
            name='mavsum',
        ),
    ]
