# Generated by Django 4.1.7 on 2023-02-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_remove_brigada_ish_turi_remove_brigada_mavsum'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoriOmbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dori_name', models.CharField(max_length=200)),
                ('narxi', models.FloatField()),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Kontragen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx_name', models.CharField(max_length=200)),
                ('maydon', models.FloatField()),
                ('sent', models.FloatField()),
                ('xosil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DoriSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.FloatField()),
                ('summa', models.FloatField()),
                ('dori_tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.doriombor')),
                ('fermer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kontragen')),
            ],
        ),
    ]
