# Generated by Django 4.1.7 on 2023-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_doriombor_kontragen_dorisend'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontragen',
            name='amaf_reja',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kontragen',
            name='kali_reja',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kontragen',
            name='karb_reja',
            field=models.FloatField(null=True),
        ),
    ]
