# Generated by Django 4.1.7 on 2023-02-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_kontragen_amaf_reja_kontragen_kali_reja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontragen',
            name='massiv',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dorisend',
            name='summa',
            field=models.FloatField(blank=True),
        ),
    ]
