# Generated by Django 4.1.7 on 2023-02-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_kontragen_massiv_alter_dorisend_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorisend',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
