# Generated by Django 4.1.7 on 2023-02-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0022_lavozim_bolim_xodimlar_ishxaqqi_xodimlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IshTur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brlik', models.CharField(choices=[('КГ', 'КГ'), ('ЛИТР', 'ЛИТР'), ('ТОННА', 'ТОННА'), ('МЕТР', 'МЕТР')], max_length=200, null=True)),
                ('narx', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IshReja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reja', models.FloatField(null=True)),
                ('mex_tur', models.CharField(choices=[("Ko'l Mexnati", "Ko'l Mexnati"), ('Texnika', 'Texnika')], max_length=200, null=True)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.brigada')),
            ],
        ),
        migrations.CreateModel(
            name='Dispasher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mex_tur', models.CharField(choices=[("Ko'l Mexnati", "Ko'l Mexnati"), ('Texnika', 'Texnika')], max_length=200)),
                ('miqdor', models.FloatField()),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.brigada')),
                ('ish_tur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.ishtur')),
            ],
        ),
    ]
