# Generated by Django 4.1.7 on 2023-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispasher',
            name='summa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
