# Generated by Django 4.1.7 on 2023-02-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_dispasher_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ishreja',
            name='brigada',
        ),
        migrations.DeleteModel(
            name='Dispasher',
        ),
        migrations.DeleteModel(
            name='IshReja',
        ),
        migrations.DeleteModel(
            name='IshTur',
        ),
    ]
