# Generated by Django 4.1.7 on 2023-02-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0022_lavozim_bolim_xodimlar_ishxaqqi_xodimlar'),
        ('information', '0003_remove_ishreja_brigada_delete_dispasher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarxnomaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
                ('brlik', models.CharField(choices=[('КГ', 'КГ'), ('ЛИТР', 'ЛИТР'), ('ТОННА', 'ТОННА'), ('МЕТР', 'МЕТР')], max_length=20)),
                ('n_narx', models.FloatField()),
                ('k_narx', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BajarilganIshlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField()),
                ('k_summa', models.FloatField()),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.brigada')),
                ('ish_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.narxnomas')),
            ],
        ),
    ]
