# Generated by Django 4.1.7 on 2023-02-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajarilganishlar',
            name='n_summa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bajarilganishlar',
            name='k_summa',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='narxnomas',
            name='k_narx',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='narxnomas',
            name='n_narx',
            field=models.FloatField(blank=True),
        ),
    ]
