# Generated by Django 4.1.7 on 2023-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_bajarilganishlar_n_summa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajarilganishlar',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
