# Generated by Django 4.1.7 on 2023-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_bajarilganishlar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='narxnomas',
            name='mex_tur',
            field=models.CharField(choices=[("Ko'l Mexnati", '1'), ('Texnika', '2')], max_length=20, null=True),
        ),
    ]
