# Generated by Django 4.1.7 on 2023-02-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_narxnomas_mex_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narxnomas',
            name='brlik',
            field=models.CharField(choices=[('КГ', 'КГ'), ('ЛИТР', 'ЛИТР'), ('ТОННА', 'ТОННА'), ('МЕТР', 'МЕТР'), ('ГА', 'ГА')], max_length=20),
        ),
        migrations.AlterField(
            model_name='narxnomas',
            name='mex_tur',
            field=models.CharField(choices=[('1', "Ko'l Mexnati"), ('2', 'Texnika')], max_length=20, null=True),
        ),
    ]
